services:
   oracle.listener:
       class: App\EventSubscriber\OracleSessionInitSubscriber
       tags:
           - { name: doctrine.event_listener, event: postConnect }

parameters:
    env(DATABASE_URL): ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
#            postgres:
#                url: '%env(POSTGRES_URI)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
