framework:
    cache:
        app: cache.adapter.pdo
        default_pdo_provider: app.cache_pdo_provider

services:
    app.cache_pdo_provider:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - {url: '%env(resolve:DATABASE_URL)%'}
