parameters:
    env(LOGGER_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: notice
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50
        nested:
            type: stream
            path: "%env(resolve:LOGGER_PATH)%"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
