parameters:
    env(LOGGER_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: notice
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50
        grouped:
            type: group
            members: ['nested', 'lark']
        nested:
            type: stream
            path: "%env(resolve:LOGGER_PATH)%"
            level: debug
        lark:
            type: service
            id: App\Monolog\LarkBotHandler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
