parameters:
    env(LOGGER_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: notice
            handler: grouped
            excluded_http_codes: [404, 405]
        grouped:
            type: group
            members: ['nested', 'feishu']
        nested:
            type: stream
            path: "%env(resolve:LOGGER_PATH)%"
            level: debug
        feishu:
            type: service
            id: App\Monolog\FeishuBotHandler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        # Uncomment to log deprecations
        #deprecation:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        #deprecation_filter:
        #    type: filter
        #    handler: deprecation
        #    max_level: info
        #    channels: ["php"]
