parameters:
    env(LOGGER_PATH): "%kernel.logs_dir%/%kernel.environment%.log"
    env(LOGGER_DEPRECATION_PATH): "%kernel.logs_dir%/%kernel.environment%.deprecations.log"

monolog:
    handlers:
        main:
            type: stream
            path: "%env(resolve:LOGGER_PATH)%"
            level: debug
            channels: ["!event"]
            excluded_http_codes: [404, 405]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%env(resolve:LOGGER_DEPRECATION_PATH)%"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
