homepage:
    path: /
    controller: App\Controller\GalleryController::archive
    methods: GET|HEAD

image:
    path: /images/{name}/
    controller: App\Controller\GalleryController::image
    requirements:
        name: '\w+'
    methods: GET|HEAD

browse:
    path: /p/{page}/
    controller: App\Controller\GalleryController::browse
    requirements:
        page: '\d+'
    methods: GET|HEAD

archive:
    path: /archives/{market}/{date}/
    controller: App\Controller\GalleryController::archive
    requirements:
        market: '[a-z]{2}-[A-Z]{2}'
        date: '\d{8}'
    methods: GET|HEAD

settings:
    path: /settings/
    controller: App\Controller\SettingsController::index
    methods: GET|HEAD|POST
