homepage:
    path: /
    controller: App\Controller\GalleryController::archive
    methods: GET|HEAD

image:
    path: /images/{name}/
    controller: App\Controller\GalleryController::image
    requirements:
        name: '\w+'
    methods: GET|HEAD

image_legacy:
    path: /Image/{name}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'image'
        permanent: true
        keepQueryParams: false
    requirements:
        name: '\w+'
    methods: GET|HEAD

browse:
    path: /p/{!page}/
    controller: App\Controller\GalleryController::browse
    requirements:
        page: '\d+'
    defaults:
        page: 1
    methods: GET|HEAD

browse_legacy:
    path: /Page/{page}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'browse'
        permanent: true
        keepQueryParams: false
    requirements:
        page: '\d+'
    methods: GET|HEAD

archive:
    path: /archives/{market}/{date}/
    controller: App\Controller\GalleryController::archive
    requirements:
        market: '[a-z]{2}-[A-Z]{2}'
        date: '\d{8}'
    methods: GET|HEAD

archive_legacy:
    path: /Archive/{market}/{date}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'archive'
        permanent: true
        keepQueryParams: false
    requirements:
        market: '[a-z]{2}-[A-Z]{2}'
        date: '\d{8}'
    methods: GET|HEAD

date:
    path: /d/{date}/
    controller: App\Controller\GalleryController::date
    requirements:
        date: '\d{8}'
    methods: GET|HEAD

date_legacy:
    path: /Date/{date}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'date'
        permanent: true
        keepQueryParams: false
    requirements:
        date: '\d{8}'
    methods: GET|HEAD

settings:
    path: /settings/
    controller: App\Controller\SettingsController::index
    methods: GET|HEAD|POST

settings_legacy:
    path: /Settings/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'settings'
        permanent: true
        keepQueryParams: false
    methods: GET|HEAD

prune:
    path: /prune/{token}/
    controller: App\Controller\CachePruningController::index
    requirements:
        token: '\d{6}'
    methods: GET
