image:
    path: /images/{name}/
    controller: App\Controller\GalleryController::image
    methods: GET|HEAD

settings:
    path: /settings/
    controller: App\Controller\SettingsController::index
    methods: GET|HEAD|POST
